version: '3.4'

services:
  apprevendedores:
    image: ${DOCKER_REGISTRY-}apprevendedores
    build:
      context: .
      dockerfile: AppRevendedores/Dockerfile
    
      
    depends_on:
      - sqlserver
    ports:
      - "5000:80"

  sqlserver:
    image: mcr.microsoft.com/mssql/server
    container_name: sqlserver
    environment:
      SA_PASSWORD: "EZEQUIEL#123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql

volumes:
  sqlserver-data:
